# docker-compose.yml
services:

  db:
    image: mariadb:11
    container_name: stella
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - interservices

  adminer:
    image: adminer:latest
    container_name: stella_admin
    depends_on:
      - db
    networks:
      - interservices

networks:
  interservices:
    external: true