# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mariadb
    container_name: db_sql
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: db_sql_admin
    restart: always
    ports:
      - 8081:8080