# docker-compose.yml
services:

  db:
    image: mariadb:11
    container_name: stella
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - interservices

  adminer:
    image: adminer:4.8.1
    container_name: stella_admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - interservices

networks:
  interservices:
    external: true
